### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#1]
Возник вопрос, в прошлом семестре на курсе по МД было требование иметь не менее 5 сущностей. Есть ли подобное требование к нашему курсовому проекту?

Вот мой пример ТЗ.

1.1. Общие сведения 
1.1.1 Наименование системы: 
Система управления тренажёрного зала. 
 
1.1.2 Наименование организации заказчика, разработчика системы: 
Заказчик: КФ МГТУ им. Н. Э. Баумана 
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-52Б Тарасов К.О. 
 
1.1.3 Плановые сроки начала и окончания работы по созданию системы: 
Плановый срок начала работ – 01.09.2023. 
Плановый срок окончания работ – 31.12.2023. 
 
1.2. Назначение и цели создания системы 
1.2.1 Назначение системы: 
Разрабатываемая система предназначена для удобной записи клиента тренажёрного зала к тренеру, которая включает в себя базу данных для хранения информации о клиентах, сотрудниках (тренерах), тренировках. 
 
1.2.2 Цели создания системы: 
Система создаётся для облегчения процесса записи на тренировку в тренажёрный зал при помощи сети интернет. 
 
 
 
 
 
 
 
 
 
 
 
 
 
1.3. Характеристика объектов автоматизации 
Система управления тренажёрного зала будет включать следующий объект автоматизации: 
- Запись клиента к тренеру 
1.4. Требования к системе 
1.4.1 Требования к системе в целом: 
Система должна быть интуитивно понятная как клиентам, так и сотрудникам 
1.4.2 Требования к функциям, выполняемым системой: 
 - Авторизация 
 - Выбор тренера 
 - Запись к тренеру 
 
1.4.3 Требования к видам обеспечения: 
 - Система управления базами данных (СУБД) для хранения и обработки данных (например, MySQL, PostgreSQL); 
 - Компьютеры и серверы для развертывания и работы системы; 
 - Сетевое оборудование для организации взаимодействия компонентов системы; 
 - Защита данных и доступа. 
 
1.5. Состав и содержание работ по созданию системы 
1.5.1 Этапы работ: 
1. Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса (1 – 4-я недели). 
2. Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД (5 – 7-я недели). 
3. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Разработка эксплуатационной документации (8 – 10-я недели). 
4. Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы (11 – 14-я недели). 
 
1.6. Порядок контроля и приемки системы 
Система разрабатывается с проведением тестирования системы на соответствие функциональным и нефункциональным требования, а также с оценкой работоспособности системы на основе результатов тестирования. 
Приемка работы, которая осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5, сопровождается проверкой соответствия системы требованиям, описанным в техническом задании. 
 
1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие 
Для подготовки системы к вводу в действие должны быть проведены следующие мероприятия: 
- Настройка сервера для обеспечения безопасности и корректности функционирования системы; 
- Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ. 
 
1.8. Требования к документированию 
Разработка сопровождается расчетно-пояснительной запиской, которая состоит из следующих частей: 
- Техническое задание в соответствии с ГОСТ 34.602-89; 
- Исследовательская часть; 
- Проектно-конструкторская часть; 
- Проектно-технологическая часть. 
 
1.9. Источники разработки 
Источники, на основании которых было составлено техническое задание: 
 - ГОСТ 34.602-89 "Техническое задание на создание автоматизированной системы".

**Comment by wldmr-key** [comment]
> Возник вопрос, в прошлом семестре на курсе по МД было требование иметь не менее 5 сущностей. Есть ли подобное требование к нашему курсовому проекту?

да

> Система управления тренажёрного зала

с падежами все хорошо?

> 1.2.1 Назначение системы:
перебор - нужно указать для кого предназначена система и, возможно, при каких обстоятельствах

> Цели создания системы

цель должна быть измерима и достидима. В чем измеряется облегчение?

> Характеристика объектов автоматизации

здесь перечисляются уже существующие объекты и процессы, которые должны быть автоматизированы для достижения цели

И я не вижу главного - требований к разрабатываемой системе - что она должна делать?

**Comment by Kirill1371** [comment]
Исправил пункты 1.2.1 , 1.2.2 , 1.3 , 1.4.1  

1.2. Назначение и цели создания системы
1.2.1 Назначение системы: 
Разрабатываемая система предназначена для удобной записи клиента тренажёрного зала к тренеру. 
Система будет удобна пользователю, т.к. сможет визуализировать процесс записи.
Система будет удобна сотрудникам, т.к. снизит нагрузку на операторов кол-центра.


1.2.2 Цели создания системы:
Система создаётся для облегчения процесса записи на тренировку в тренажёрный зал при помощи сети интернет, что позволит разгрузить операторов кол-центра, а также сведёт к нулю время ожидания пользователя.


1.3. Характеристика объектов автоматизации
Система управления тренажёрным залом будет включать следующие объекты автоматизации:
- Учёт клиентов, учёт тренеров, составление расписания занятий.
1.4. Требования к системе
1.4.1 Требования к системе в целом:
Система должна обеспечивать эффективное управление взаимодействия клиента и тренеров тренажёрного зала.
Система должна быть интуитивно понятной и простой в использовании, чтобы персонал тренажёрного зала мог быстро освоить ее без необходимости длительного обучения.
Система должна быть надежной и безопасной, обеспечивая конфиденциальность данных клиентов.
1.4.2 Требования к функциям, выполняемым системой:
   - Авторизация
   - Выбор тренера
   - Запись к тренеру

**Comment by Kirill1371** [comment]
@wldmr-key

**Comment by wldmr-key** [comment]
функции для клиента поняты и приняты. А для работников какие должны быть реализованы функции?

**Comment by Kirill1371** [comment]
Добавил в пункт 1.4.2 функции для сотрудников. 
Появился вопрос про требования к системе с производственной точки зрения : Вы говорили что указано в ТЗ - за то и будут спрашивать (мол указал хостинг - покупай адрес). Свой пункт 1.4.3 я просто скопировал, и вполне вероятно, что он не будет выполнен в полном объёме, надо ли его переделать или всё же невыполнение некоторых требований не повлияет на оценку?

1.4.3 Требования к видам обеспечения:
- Система управления базами данных (СУБД) для хранения и обработки данных  (например, MySQL, PostgreSQL);
  	 - Компьютеры и серверы для развертывания и работы системы;
 - Сетевое оборудование для организации взаимодействия компонентов системы;
 - Защита данных и доступа.

1.4.2 Требования к функциям, выполняемым системой:
Для клиента:
 	- Авторизация
   	- Выбор тренера
  	- Запись к тренеру
	Для сотрудников:
	- Авторизация
	- Просмотр актуального расписания
	- Выбор рабочего дня

**Comment by wldmr-key** [comment]
> или всё же невыполнение некоторых требований не повлияет на оценку

никогда не пиши, что не можешь выполнить ))

> Для сотрудников

а, откуда берется информация о тренерах? ценах? залах? ....

**Comment by Kirill1371** [comment]
Информация о тренерах будет записана изначально и поддерживаться актуальной администратором. Информация о самом зале и о ценах на абонемент будет написана на сайте, но купить через сайт невозможно. Во всех ФК эта процедура производится на месте. В целом, мною будут помимо дизайна реализовываться авторизация и запись, с разницей последней функции для тренера и для клиента.

Пункт 1.4.3 тогда изменю чуть позже, когда определюсь с ЯП.

**Comment by wldmr-key** [comment]
> Информация о тренерах будет записана изначально и поддерживаться актуальной администратором. 

Стоп! Каким образом? Через pgAdmin? ))

**Comment by Kirill1371** [comment]
Ну да. Когда запускается новый ФК клуб, то сначала набирается штат, поэтому информация по сотрудникам будет на страницах сайта и в БД. А если разработка для уже функционирующего ФК - то тем более информация будет.

**Comment by wldmr-key** [comment]
это был сарказм. Конечно, никакие pgAdmin недопустимы иначе в ТЗ требования к квалификации стоило писать по-другому.

Тренеры могут увольняться и приниматься на работу, у них может быть отпуск или болезнь, вместимость зала и количество тренажеров ограничено - где все это отражается?

**Comment by Kirill1371** [comment]
Если тренер уволен, болеет, в отпуске - то кнопка записи к нему будет заблокирована. Если на групповое занятие записалась 20 человек, то кнопка также будет скрыта.
По поводу занятий с тренером, повторюсь, преимуществ в очереди на тренажёры такие клиенты не имеют. И в целом, вести запись на тренажёры не имеет смысла, потому что тренировка меняется уже в процессе, не получилось у Вас пожать штангу, Вы решили заменить на это занятие жим штанги жимом блока. Такое явление повсеместно, поэтому ни записи на тренажёры, ни записи на вход ни один ФК не ведёт.

**Comment by wldmr-key** [comment]
> Если тренер уволен, болеет, в отпуске - то кнопка записи к нему будет заблокирована. Если на групповое занятие записалась 20 человек, то кнопка также будет скрыта.

Кем? Есть такая функция?

> По поводу занятий с тренером, повторюсь

ок, твои дела ))

**Comment by Kirill1371** [comment]
Я сделаю функцию недоступности кнопки записи на групповое занятие при его заполненности. А занятое клиентом на индивидуальное занятие время будет недоступно для выбора. Точно так же не будет доступна запись к тренеру, которого нет на рабочем месте в этот день (отпуск, болезнь, отставка)

**Comment by wldmr-key** [comment]
сфоомулируй все это в требованиях к функциям

**Comment by Kirill1371** [comment]
Наши с Вами доработки включил в пункт 1.4.2, если я ошибся, и следует внести в другой пункт - сообщите мне.
1.4.2 Требования к функциям, выполняемым системой:
Для клиента:
 	- Авторизация
   	- Выбор тренера
  	- Запись к тренеру
        **- Отсутствие возможности записи на занятие в случае заполненности или в любом другом описанном ниже**
	Для сотрудников:
	- Авторизация
	- Просмотр актуального расписания
	- Выбор рабочего дня
        **- Изменение сведений о себе (отпуск, больничный, увольнение)**

**Comment by wldmr-key** [comment]
> Просмотр актуального расписания

а,откуда берется актуальное расписание? С неба?

> Выбор рабочего дня

это как?

> Отсутствие возможности записи на занятие в случае заполненности или в любом другом описанном ниже

это не функция, а соображение здравого смысла. Не включай

**Comment by Kirill1371** [comment]
_Как мы с вами и условились при личной встрече, актуальное расписание будет составляться по ходу заполнения индивидуальных тренировок. Финальный вариант ТЗ для первого этапа:_

1.1. Общие сведения
     1.1.1 Наименование системы: 
Система управления тренажёрным залом.

1.1.2 Наименование организации заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-52Б Тарасов К.О.

1.1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ – 01.09.2023.
Плановый срок окончания работ – 31.12.2023.

1.2. Назначение и цели создания системы
1.2.1 Назначение системы: 
Разрабатываемая система предназначена для удобной записи клиента тренажёрного зала к тренеру. 
Система будет удобна пользователю, т.к. сможет визуализировать процесс записи.
Система будет удобна сотрудникам, т.к. снизит нагрузку на операторов кол-центра.


1.2.2 Цели создания системы:
Система создаётся для облегчения процесса записи на тренировку в тренажёрный зал при помощи сети интернет, что позволит разгрузить операторов кол-центра, а также сведёт к нулю время ожидания пользователя.


1.3. Характеристика объектов автоматизации
Система управления тренажёрным залом будет включать следующие объекты автоматизации:
- Учёт клиентов
- Учёт тренеров
- Составление расписания занятий

1.4. Требования к системе
1.4.1 Требования к системе в целом:
Система должна обеспечивать эффективное управление взаимодействия клиента и тренеров тренажёрного зала.
Система должна быть интуитивно понятной и простой в использовании, чтобы персонал тренажёрного зала мог быстро освоить ее без необходимости длительного обучения.

1.4.2 Требования к функциям, выполняемым системой:
Для клиента:
 	- Авторизация
   	- Выбор тренера
  	- Запись к тренеру
	Для сотрудников:
	- Авторизация
	- Просмотр актуального расписания
	- Выбор рабочего дня
        - Изменение сведений о себе (отпуск, больничный, увольнение)



1.5. Состав и содержание работ по созданию системы
1.5.1 Этапы работ:
1. Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса (1 – 4-я недели).
2. Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД (5 – 7-я недели).
3. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Разработка эксплуатационной документации (8 – 10-я недели).
4. Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы (11 – 14-я недели).


1.6. Порядок контроля и приемки системы
Система разрабатывается с проведением тестирования системы на соответствие функциональным и нефункциональным требования, а также с оценкой работоспособности системы на основе результатов тестирования. 
Приемка работы, которая осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5, сопровождается проверкой соответствия системы требованиям, описанным в техническом задании.

1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
Для подготовки системы к вводу в действие должны быть проведены следующие мероприятия:
- Настройка сервера для обеспечения безопасности и корректности функционирования системы;
- Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.

1.8. Требования к документированию
Разработка сопровождается расчетно-пояснительной запиской, которая состоит из следующих частей:
- Техническое задание в соответствии с ГОСТ 34.602-89;
- Исследовательская часть;
- Проектно-конструкторская часть; 
- Проектно-технологическая часть.

1.9. Источники разработки
Источники, на основании которых было составлено техническое задание:
 	- ГОСТ 34.602-89 "Техническое задание на создание автоматизированной системы".
 

_Можем закрывать?_

**Comment by wldmr-key** [comment]
> Можем закрывать?

пока нет

Назначение - для **кого** предназначена система?

Цель - почему за ее разработку и поддержку заплатят?

Характеристика объектов автоматизации - что существует без системы

ТЗ не должно включать будущего времени - это задание

По функциям:
сформулируй аккуратнее - что такое выбор рабочего дня? Откуда в системе появляются тренеры? 

В ТЗ нет ни слова о том, что тренировки бывают групповые и индивидуальные

**Comment by Kirill1371** [comment]
_Отредактировал пункты назначения, целей, характеристики. Под выбором рабочего дня я подразумеваю "запись клиента" наоборот, т.е. тренер вручную выберет день, когда он будет на работе. Тренеры в системе авторизуются как и клиенты._

1.2.1 Назначение системы: 
	Система предназначен для клиентов фитнес-клуба.
Система будет удобна пользователю, т.к. сможет визуализировать процесс записи.
Система будет удобна сотрудникам, т.к. снизит нагрузку на операторов колл-центра.

1.2.2 Цели создания системы:
	Система создаётся для реализации функции записи клиента к тренеру посредством веб-приложения. Данная система записи существует далеко не во всех фитнес-клубах.

1.3. Характеристика объектов автоматизации
Система управления тренажёрным залом будет включать следующие объекты автоматизации:
- Учёт клиентов
- Учёт тренеров
- Составление расписания занятий
- Запись на индивидуальные и групповые тренировки

**Comment by wldmr-key** [comment]
> _Отредактировал пункты назначения, целей, характеристики. Под выбором рабочего дня я подразумеваю "запись клиента" наоборот, т.е. тренер вручную выберет день, когда он будет на работе. Тренеры в системе авторизуются как и клиенты._
> 

тут есть проблема. Спортзалу нужно, чтобы каждый час его работы в зале присутствовал хоть один тренер. Как быть?

> 1.2.1 Назначение системы: Система предназначен для клиентов фитнес-клуба. Система будет удобна пользователю, т.к. сможет визуализировать процесс записи. Система будет удобна сотрудникам, т.к. снизит нагрузку на операторов колл-центра.

предложения с будущим временем никогда не употребляются в задании. Убери, они не нужны. Первое предложение тоже нужно заменить система предназначена не для клиентов. Не они за нее заплатят

> 
> 1.2.2 Цели создания системы: Система создаётся для реализации функции записи клиента к тренеру посредством веб-приложения. Данная система записи существует далеко не во всех фитнес-клубах.

второе предложение не относится к цели. Первое - не может быть целью, так как функция записи уже есть в фитнес-клубе

> 
> 1.3. Характеристика объектов автоматизации Система управления тренажёрным залом будет включать следующие объекты автоматизации:
> 
> * Учёт клиентов
> * Учёт тренеров
> * Составление расписания занятий
> * Запись на индивидуальные и групповые тренировки

опять будущее время. "Объектами автоматизации являются... = продолжи предложение

**Comment by Kirill1371** [comment]
_Тренеры сами распределяют между собой дежурства, если возникнет форс-мажор и тренер не сможет дежурить он всего-навсего попросит своего коллегу поменяться. Для ФК в целом это не является проблемой, но при этом и не будет загружать нашу систему не нужной информацией._ 
**Вариант 1го предложения пункта 1.2.1:** "Система предназначена для фитнес-клуба."
_По поводу Вашего замечания пункта 1.2.2, функция записи действительно существует, но лишь по сотовой связи (и как я Вам продемонстрировал в анализе аналогов моей функции нет в большинстве ФК) . Я же конкретно оговариваю что запись будет реализована в веб-приложении._ 
"Объектами автоматизации являются учёт клиентов, учёт тренеров, составление расписания занятий, запись на индивидуальные и групповые тренировки."

**Comment by wldmr-key** [comment]
> По поводу Вашего замечания пункта 1.2.2, функция записи действительно существует, но лишь по сотовой связи (и как я Вам продемонстрировал в анализе аналогов моей функции нет в большинстве ФК) . Я же конкретно оговариваю что запись будет реализована в веб-приложении.

#$%^#^%!!!! Пойми разницу между целью и функцией!!!
Целью макдональдса не является приготовление бургеров. Целью банка не является выдача кредитов. Целью стрелка не является зарядка ружья. Продолжать?

**Comment by Kirill1371** [comment]
Цель: привлечение клиентов

**Comment by wldmr-key** [comment]
в чем выражается привлечение клиентов и зачем оно нужно?

**Comment by Kirill1371** [comment]
Привлечение клиентов выражается в удобном функционале веб-приложения, которого нет у конкурентов. Привлечение клиентов нужно для раскрутки бренда и зарабатывания денег.

**Comment by wldmr-key** [comment]
неверный ответ

**Comment by Kirill1371** [comment]
Цель: система создаётся для привлечения клиентов путём автоматизации процесса записи клиента к тренеру тренажёрного зала.

**Comment by wldmr-key** [comment]
хотя бы так. Это, во всяком случае, можно измерить
