### ISSUE TITLE
Добавления в исследовательскую часть

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#10]
3.1 Постановка задачи проектирования
Цель задачи данной курсовой работы заключается в создании системы управления записями на тренировки фитнес-клуба. Эта система должна предоставлять возможности регистрации и аутентификации пользователей, записи к тренеру и отслеживания актуального расписания, удаления при необходимости созданной записи для клиента; выбор рабочего дня, отслеживание актуального расписания и удаление как тренировок, так и рабочих дней для тренера.
Задача проектирования такой системы может быть решена при помощи следующих средств разработки: веб-сервера webpack-dev-server, языка программирования JavaScript, фреймворков NodeJS, Express, базы данных: MongoDb, а проектирование пользовательского интерфейса: HTML, JavaScript, фреймворка React.

3.5 Обоснование выбора инструментов и платформы для разработки
Выбор инструментов и платформы для разработки проекта на стеке MERN (язык JavaScript, фреймворки Express, NodeJs, React и база данных Mongodb) обусловлен рядом причин:
1.	JavaScript - это современный объектно-ориентированный язык программирования. Он имеет множество преимуществ, таких как высокая производительность, удобный синтаксис, использование одного языка и для фронт-разработки и для бэкенд-разработки.
2.	База данных MongoDb - это высокопроизводительная NoSQL база данных, которая позволяет хранить и обрабатывать данные в реальном времени. Она обеспечивает высокую надежность и безопасность данных, а также удобный интерфейс для управления всеми функциями. База данных MongoDB позволяет разработчикам быстро создавать приложения с возможностью синхронизации данных между клиентскими и серверными приложениями в режиме реального времени. Она также поддерживает множество инструментов для работы с данными, таких как запросы, фильтры и сортировки, что делает ее очень гибкой и мощной. База данных MongoDB является одним из ключевых инструментов для разработки высококачественных приложений на стеке MERN.
3.	Использование языка JavaScript, фреймворков Express, NodeJs, React и базы данных Mongodb позволяет создавать высококачественные и мощные приложения, которые могут работать на различных платформах. Это позволяет увеличить охват аудитории и расширить возможности приложения.
4.	Кроме того, JavaScript, Express, NodeJs, React, Mongodb имеют активное сообщество разработчиков, что обеспечивает поддержку и развитие этих инструментов в будущем.
Таким образом, выбор инструментов и платформы для разработки проекта на языке JavaScript, фреймворков Express, NodeJs, React и базы данных Mongodb обусловлен высокой производительностью, мощными функциями и возможностью создания кроссплатформенных приложений.

3.6 Перечень задач, подлежащих решению в процессе разработки
Задачи, подлежащие решению в процессе разработки:
1.	Исследование предметной области: необходимо провести исследование предметной области фитнес-клубов, чтобы понимать особенности работы залов и потребности клиентов. Это поможет определить требования к системе и ее функциональность.
2.	Проектирование архитектуры системы: на основе требований к системе необходимо разработать архитектуру системы, определить ее компоненты и связи между ними. Это поможет обеспечить своевременную работу системы и удобство использования для пользователей.
3.	Разработка системы регистрации и аутентификации: необходимо разработать систему регистрации и аутентификации пользователей, чтобы обеспечить безопасность данных и защиту от несанкционированного доступа к системе.
4.	Реализация управления записями как клиентов так и тренеров: необходимо реализовать функциональность, позволяющую тренерам управлять своими рабочими днями и при необходимости отменять тренировки. Клиенты должны иметь возможность записаться на определенные дату и время на тренировку к определённому тренеру через систему.
5.	Тестирование и отладка системы: необходимо провести тестирование системы и отладить ее, чтобы обеспечить ее стабильную работу и отсутствие ошибок. Тестирование должно включать проверку функциональности, безопасности и удобства использования системы.

**Comment by wldmr-key** [comment]
> управления информацией о гостинице, управления номерами и бронированиями,

ну-ну

**Comment by Kirill1371** [comment]
Исправил опечатки.
_Эта система должна предоставлять возможности регистрации и аутентификации пользователей, записи к тренеру и отслеживания актуального расписания, удаления при необходимости созданной записи для клиента; выбор рабочего дня, отслеживание актуального расписания и удаление как тренировок, так и рабочих дней для тренера._
