### ISSUE TITLE
Введение/заключение

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#11]
1.Введение
Спортивные залы в последние годы набирают всё большую популярность. Вместе с тем не всегда на высокий спрос есть качественное предложение. Так получилось и в нашем случае. К сожалению, в большинстве фитнес-клубах отсутствует запись к тренеру через сайт или приложение. Вместо этого единственным способом является звонок в колл-центр и связь с оператором, который узнает актуальное расписание нужного Вам тренера и внесёт необходимую запись. Такой подход имеет несколько существенных минусов: 
1) связь с оператором может потребовать ожидания
2) любое изменение ранее сделанной Вами записи также через оператора
3) отсутствие возможности визуализировать запись, т.е. увидеть календарь с существующими отметками.
Моё решение будет заключаться в том, что Вы сами сможете записаться и редактировать свою запись в веб-приложении. Это сэкономит Ваше время, поможет составить расписание, визуализировав этот процесс и оставит приятное впечатление о технологичном сайте заказчика.

Заключение
При выполнении курсовой работы на тему «Приложение фитнес клуба» была исследована и описана предметная область, проведен анализ аналогов данной системы, а также выбор инструментов и платформы для разработки. 
Проведен анализ объектов автоматизации и разработаны методы решения 
технических задач. Также была разработана и реализована структура базы 
данных, серверная часть приложения и веб-интерфейс системы. База данных 
была наполнена тестовыми данными. 
Результатом данной курсовой работы является рабочее веб-приложения для записи клиентов на тренировки и управления расписанием тренерами.

**Comment by wldmr-key** [comment]
Норм, но я бы убрал второе лицо (Вы, Ваш) во введении

**Comment by Kirill1371** [comment]
Убрал
