### ISSUE TITLE
Предметная область

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#3]
Предметная область.
Спортивные залы в последние годы набирают всё большую популярность. Вместе с тем не всегда на высокий спрос есть качественное предложение. Так получилось и в нашем случае. К сожалению, в большинстве фитнес-клубах отсутствует запись к тренеру через сайт или приложение. Вместо этого единственным способом является звонок в колл-центр и связь с оператором, который узнает актуальное расписание нужного Вам тренера и внесёт необходимую запись. Такой подход имеет несколько существенных минусов: 
1) связь с оператором может потребовать ожидания
2) любое изменение ранее сделанной Вами записи также через оператора
3) отсутствие возможности визуализировать запись, т.е. увидеть календарь с существующими отметками.
Моё решение будет заключаться в том, что Вы сами сможете записаться и редактировать свою запись в веб-приложении. Это сэкономит Ваше время, поможет составить расписание, визуализировав этот процесс и оставит приятное впечатление о технологичном сайте заказчика)

**Comment by wldmr-key** [comment]
Это не описание предметной области, а агитка. Вполне сойдет для введения, если ты уберешь второе лицо - "Это сэкономит Ваше время" - это ты с кем рахговариваешь? ))

**Comment by Kirill1371** [comment]
Мне казалось, что у нас диалог с заказчиком)
В любом случае вот более прагматичная версия
Предметная область
Фитнес-клуб – место для занятий спортом. Как правило в них работают несколько тренеров, работающих по графику. Из-за ограниченности размеров зала, руководством предусматриваются как групповые занятия с тренером, так и индивидуальные, при этом есть возможность самостоятельного посещения зала. Всё взаимодействия клиент-ФК происходит либо через оператора колл-центра, либо через веб-приложение. Запись веб-приложении происходит только после авторизации клиента. Клиент в праве назначить индивидуальную тренировку или выбрать групповую с помощью удобного календаря.

**Comment by wldmr-key** [comment]
все хорошо, но опять всплывает твое приложение!!! Забудь про него здесь!
Лучше напиши, какие требования к составлению расписания тренеров и ограничения на запись клиентов

**Comment by Kirill1371** [comment]
В один день работает несколько тренеров, тренер может вести одного клиента в час. Занятие длится один астрономический час.

**Comment by wldmr-key** [comment]
а групповые занятия? А вместимость зала? А ограничения по оборудованию?

**Comment by Kirill1371** [comment]
На групповых занятиях максимум 20 человек. По моему опыту вместимость зала нигде не обговаривается, нет никаких ограничений на количество людей или использования оборудования. Всё проще: пришёл, если много людей - подождал пока кто-то освободит тренажёр или ушёл сам. Это же не английский клуб, где для вступления необходимо заручиться поддержкой двух его участников)) тут всё проще.

**Comment by wldmr-key** [comment]
> Всё проще: пришёл, если много людей - подождал

эти случаи вообще мимо твоей системы - это для тех, кто экономит на тренерах. Если ты забронировал время работы с тренером, то такой вариант не проходит

**Comment by Kirill1371** [comment]
Наличие записи к тренеру не является бронью на жимовую лавку, к примеру. Это опять-таки вытекает из личного опыта. Поэтому клиент с записью к тренеру от к клиента с свободным посещением отличаются лишь человеком, который будет стоять над ним и говорить что делать.

**Comment by wldmr-key** [comment]
ок

**Comment by Kirill1371** [comment]
_Учитывая Ваши советы составил финальную версию предметной области на первый этап:_

Фитнес-клуб – место для занятий спортом. Как правило в них работают несколько тренеров, работающих по графику. Из-за ограниченности размеров зала, руководством предусматриваются как групповые занятия с тренером численностью не более 20 человек, так и индивидуальные, при этом есть возможность самостоятельного посещения зала. Клиент вправе назначить индивидуальную тренировку или выбрать групповую с помощью удобного календаря. В один день работает несколько тренеров, тренер может вести одного клиента в час. Занятие длится один астрономический час. Для ФК все клиенты равны. Каждый клиент самостоятельно выбирает тренажёр, сотрудники не вправе ограничивать его во времени пользования им.

_Можем закрывать?_

**Comment by wldmr-key** [comment]
Где-то нужно сформулировать требования к системе - например, во время работы зала там по расписанию должен быть хоть один тренер. Как системе реагирует на болезнь тренера - что происходит с записями. Как индицируется, допустим, отпуск тренера. Как определяются часы и дни работы?

**Comment by Kirill1371** [comment]
_Замечание про дежурство хотя бы одного тренера добавлю. Если тренер не будет проводить занятие (заболеет, загрустит и пр.) - то он удалит запись. Отпуск тренера, а также часы его работы в конкретный день определяется тренерами между собой. Поэтому каждый из тренеров будет раз в неделю проставлять рабочие дни и часы своей работы._

**Comment by wldmr-key** [comment]
звучит жутковато. Посмотрим, как это юудет выглядеть в оформленном тексте

**Comment by Kirill1371** [comment]
_Оформленная предметная область:_
Фитнес-клуб – место для занятий спортом. Как правило в них работают несколько тренеров, работающих по графику. Из-за ограниченности размеров зала, руководством предусматриваются как групповые занятия с тренером численностью не более 20 человек, так и индивидуальные, при этом есть возможность самостоятельного посещения зала. Клиент вправе назначить индивидуальную тренировку или выбрать групповую с помощью удобного календаря. В один день работает несколько тренеров, тренер может вести одного клиента в час. Занятие длится один астрономический час. Для ФК все клиенты равны. Каждый клиент самостоятельно выбирает тренажёр, сотрудники не вправе ограничивать его во времени пользования им. Каждый день в зале находится дежурный тренер. Если тренер не будет проводить занятие (заболеет, загрустит и пр.) - то он удаляет запись. Отпуск тренера, а также часы его работы в конкретный день определяются тренерами между собой. Каждый из тренеров раз в неделю проставляет рабочие дни и часы своей работы. Система ФК хранит данные пользователя (ФИО, номер телефона), тренера (ФИО, номер телефона), запись на занятие (дату, время, вид, кол-во мест), расписание.

**Comment by wldmr-key** [comment]
Есть нестыковка:
1) Каждый день в зале находится дежурный тренер. 
2) Каждый из тренеров раз в неделю проставляет рабочие дни и часы своей работы.

как этого добиться?

И, да, горизонт планирования для клиентов и тренеров - неделя?

**Comment by Kirill1371** [comment]
Тренеры - взрослые люди с коммуникативными навыками, они смогут договориться кто из них когда дежурит. Горизонт планирования - неделя. Хотя на самом деле, конечно же, бывает что и за несколько часов всё меняется. Но я оставлю стандартно неделю.

**Comment by wldmr-key** [comment]
то есть, система не отслеживает, что в следующую субботу никто не дежурит?

**Comment by Kirill1371** [comment]
Совершенно верно

**Comment by wldmr-key** [comment]
зря

**Comment by Kirill1371** [comment]
В таком случае можем закрывать этот ишус?
