### ISSUE TITLE
Концептуальная схема

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#5]

**Comment by Kirill1371** [comment]
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/f6daadef-3a95-4ff0-baa6-348743bfa3fa)

Пояснения: 
И.Занятие – Индивидуальная тренировка
Гр.Занятие – Групповая тренировка
Дата/Вр.Начала/Вр.Конца – Дата занятия, время начала и время окончания.
Примечание: 
Мне представляется такая схема сущностей, возможно я одну из сущностей не указал или указал что она атрибут. Буду рад, если Вы обратите на это моё внимание.

**Comment by wldmr-key** [comment]
ID в концептуальной схеме излишни
У тренеров есть расписание работы?
Вид занятия это атрибут или сущность?
у тренеров есть специализация по видам занятий?
названия сущностей лучше писать во множественном числе?
запись на занятие и посещение занятия отличаются?
деньги не считаем?

**Comment by Kirill1371** [comment]
__Переработал схему. Напоминаю к чему с Вами пришли на личной встрече : расписания тренера - отдельная сущность; вид занятия - атрибут; специализация есть у занятия, а тренеры - универсальны; названия сущностей лучше в единственном числе, деньги и посещение считать не будем.__
_Можем закрывать?_

![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/77171914-0eea-46c5-b69b-b5371b8bf943)

**Comment by wldmr-key** [comment]
Все стало значительно лучше

Проблемы:
названия сущностей лучше писать во множественном числе
недоступность тренера (болезнь, отпуск) не индицируется
запись клиента на групповые занятия не правильна (судя по твоим стрелкам на групповое занятие может прийти только один клиент)

**Comment by Kirill1371** [comment]
_Добавил Ваши замечания в схему. Если к тренеру нельзя записаться - то записи просто не будет. Разве это можно как-то отобразить в схеме?_
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/fceda688-baf2-414c-887b-768b2b16ed72)

**Comment by shiiishov** [comment]
Можно как вариант добавить атрибут "статус" для тренера. Удобно для вывода на сайте) сразу понятно будет к кому можно записаться

**Comment by wldmr-key** [comment]
все атрибуты должны быть в описании предметной области

Доделай предметную область до конца. Без этого схема имеет мало смысла

**Comment by Kirill1371** [comment]
_добавил атрибуты в предметную область._

**Comment by wldmr-key** [comment]
замечание, скорее, к предметной области, чем к схеме. Видится целесообразным отметка тренерами фактического посещения занятий. Это влияет, прежде всего, на учет оплаты, кроме того достаточно существенен учет отказов от записи

**Comment by Kirill1371** [comment]
Мы с Вами посовещались и решили не считать деньги.

**Comment by wldmr-key** [comment]
Поставлю вопрос по другому. Что происходит при отказе клиента от занятия?

**Comment by Kirill1371** [comment]
Если отказ от индивидуального - время освобождается и становится видимым для всех. Если от группового - освобождается одно место

**Comment by wldmr-key** [comment]
пусть

**Comment by Kirill1371** [comment]
В таком случае можем закрывать этот ишус?

**Comment by wldmr-key** [comment]
воля твоя ))
это ж твой репозиторий ))
