### ISSUE TITLE
Анализ аналогов

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#6]

**Comment by Kirill1371** [comment]
Разберём Grand Fitness.
Для просмотра групповых занятий необходимо авторизоваться. 
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/24f07f9b-68e9-47a4-a69d-cc43697efab3)
После этого у нас появляется расписание групповых занятий и возможность записаться.
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/bf8dad67-e934-4ed7-842e-fad0f08f0c0a)

**Comment by wldmr-key** [comment]
это все? ))

**Comment by Kirill1371** [comment]
Из интересующих нас данных - да. К сожалению не смогу показать процесс записи на групповые тренировки, т.к. мой абонемент закончился.

**Comment by wldmr-key** [comment]
я имел в виду количество аналогов. Может, еще поищешь?

**Comment by Kirill1371** [comment]
ФК Атмосфера: есть вариант покупки абонемента на занятие с тренером, но выбор тренера на сайте не реализован
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/88b31a5a-0a1d-43e7-953a-99557f920696)
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/9f547275-ab96-448a-a0d9-ec78aa613f95)
ФК Джой Фит: есть статья какими качествами должен обладать тренер, но записи через сайт нет.
ФК ЗеттаСпорт как таковым сайтом не обладает, есть ссылки на группу в ВК, но и там лишь предложение покупки занятия/абонемента к тренеру без записи.

**Comment by wldmr-key** [comment]
отлично. И свои выводы в конце

**Comment by Kirill1371** [comment]
Вывод: на рынке ФК необходима функция записи к тренеру через веб-приложение.
