### ISSUE TITLE
Прототип

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#7]

**Comment by Kirill1371** [comment]
_Вам подойдут скриншоты из только начатого прототипа?_
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/4d2d718a-50d9-4c09-a86a-d492a83fb3e2)

![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/206d27ee-325a-4ca1-a3cd-47beef24ee97)

**Comment by wldmr-key** [comment]
мне все подойдет ))

это не войдет в курсовую. Скетчи нужны больше вам, чтобы определить, правильо ли вы определили и поисали атрибуты

**Comment by Kirill1371** [comment]
также планирую добавить в NavBar( синяя полоса сверху) кнопки перехода на страницы записи групповых тренировок и расписание. Пока застрял на реализации индивидуальных записей, поэтому не добавил эти страницы в NavBar на скриншотах выше.
