### ISSUE TITLE
Проектно-конструкторская часть

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#8]
_Как я понял проектно-конструкторская часть состоит из следующих этапов, поэтому я постарался отобразить эти этапы своей системы в тексте ниже. Пункт 4.3 пока не заполнил, т.к. мы решили, что фронт нуждается в доработке. В ЭОС пока выложу этот вариант, а если придётся исправлять - дополню._

4.Проектно-конструкторская часть
4.1. Разработка структуры приложения 
В центре веб-приложения находится база данных, которая служит основным источником информации. База данных содержит все необходимые данные о клиентах, тренерах, записях, сделанных клиентами или тренерами, расписаниях. Приложение написано полностью на JavaScript. Клиентская часть отвечает за взаимодействие пользователя с веб-приложением. Она обрабатывает события пользователя, такие как выбор даты и отправка запроса на запись, получение сведений из базы (расписание), а далее отправляет запросы на сервер. Серверная часть обрабатывает отправленные пользователем запросы. Она принимает данные от пользователя и выполняет необходимую бизнес-логику. Бизнес-логика включает в себя проверку доступности даты, времени у тренера, сохранение информации о записи в базе данных. Например, при получении запроса на запись тренировки, сервер проверит, доступно ли эти дата и время у конкретного тренера, сравнивая информацию в базе данных. Если запись невозможна - сервер отвечает клиенту соответствующим уведомлением. Если запись возможна, сервер сохраняет информацию о записи в базе данных и уведомляет пользователя.

4.2 Логическая модель для NoSQL БД
 
4.3 Разработка интерфейса взаимодействия пользователя с системой

4.4 Разработка архитектуры приложения
Для разработки данного веб-приложения используется клиент-серверная архитектура. В этой модели функциональность приложения разделена между клиентской и серверной частями. Клиентская часть отвечает за отображение пользовательского интерфейса и взаимодействие с пользователем. Серверная часть обрабатывает бизнес-логику, обеспечивает доступ к данным и выполняет другие вычислительные задачи. В данном приложении в качестве основного сервера используется webpack-dev-server. Это удобный сервер разработки с горячей перезагрузкой Для управления базами данных используется MongoDB. С его помощью можно управлять структурой данных и содержимым базы данных, создавать таблицы.

**Comment by Kirill1371** [comment]
4.2 Логическая модель для NoSQL БД
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/23efc2d5-5dff-47a3-9204-757510a14cfb)

**Comment by wldmr-key** [comment]
надеюсь, ты понимаешь, что это ни разу не логическая схема ))

**Comment by Kirill1371** [comment]
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/05d96fe2-9152-4040-b37e-6487a29daf61)

**Comment by wldmr-key** [comment]
какие внешние ключи для NoSQL????

**Comment by Kirill1371** [comment]
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/849e0d53-a541-40d7-8e17-85446a213bd6)

**Comment by wldmr-key** [comment]
логика абсолютно непонятна (и, да не согласуется с концептуальной схемой). Тройных связей даже в NoSQL не бывает? Что это за сущность расписание?

Не уверен, что в логической схеме сетевой модели стоит указывать id (тем более в монге это _id)

**Comment by Kirill1371** [comment]
Согласовал концептуальную и логические схемы, а также добавил пояснения к логической схеме
_3.4 Концептуальная схема_
 
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/368d7521-3a7a-444b-82e4-475e254d28dc)

_4.2 Логическая схема базы данных для NoSQL БД_

![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/3652486b-0a39-4abe-ac57-b175f26a5779)

_На рисунке ? представлена логическая схема базы данных.
Таблица «Клиент» содержит информацию о пользователях. В ней хранятся данные об идентификаторе, полном имени и электронной почте.
Связь «Один ко многим» между таблицами «Клиент» и «Запись на занятие» означает, что каждому клиенту могут соответствовать несколько записей в таблице «Запись на занятие».
Связь «Один ко многим» между таблицами «Клиент» и «Расписание_К» означает, что каждому клиенту могут соответствовать несколько записей в таблице расписания.
Таблица «Тренер» содержит информацию о пользователях. В ней хранятся данные об идентификаторе, полном имени и электронной почте.
Связь «Один ко многим» между таблицами «Тренер» и «Запись на занятие» означает, что каждому тренеру могут соответствовать несколько записей в таблице «Запись на занятие».
Связь «Один ко многим» между таблицами «Тренер» и «Расписание_Т» означает, что каждому тренеру могут соответствовать несколько записей в таблице расписания.
Связь «Один ко многим» между таблицами «Тренер» и «Рабочий день» означает, что каждому тренеру могут соответствовать несколько записей в таблице рабочего дня.
Таблица «Рабочий день» содержит информацию о днях, в которые работает тренер. В ней хранятся данные об идентификаторе, дате и времени, клиенте и тренере.
Таблица «Расписание_К» содержит информацию о тренировках. В ней хранятся данные об идентификаторе, дате и времени тренировки, клиенте и тренере.
Таблица «Расписание_Т» содержит информацию о тренировках и рабочих днях тренера. В ней хранятся данные об идентификаторе, дате и времени тренировки, клиенте и тренере, рабочих днях.
Таблица «Запись на занятие» содержит информацию о тренировках. В ней хранятся данные об идентификаторе, дате и времени тренировки, клиенте и тренере.
Связь «Один ко многим» между таблицами «Расписание_К» и «Запись на занятие» означает, что расписанию одного человека могут соответствовать несколько записей в таблице записи на занятие.
Связь «Один ко многим» между таблицами «Расписание_Т» и «Запись на занятие» означает, что расписанию одного человека могут соответствовать несколько записей в таблице записи на занятие._

**Comment by wldmr-key** [comment]
я тебя, возможно, расстрою, но уже на уровне концептуальной схемы - полнейшая жесть. Зачем нужно это адское дублирование атрибутов в записи и обоих расписаниях?

**Comment by Kirill1371** [comment]
Вы сказали, что схемы малопонятны, именно поэтому я и отразил на схеме все атрибуты

**Comment by wldmr-key** [comment]
не вижу противоречий. В первом случае они непонятны, поэтому, их публиковать нельзя. Во втором случае они неправильны

**Comment by Kirill1371** [comment]
Концептуальная схема должна быть похожа на это?
![SmartSelect_20231203_164849_GitHub.jpg](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/81003a16-85d5-45ad-b73c-a4b13138caa7)

Без атрибутов?

Мне казалось, что концептуальная схема должна отображать хранение информации в БД (с помощью отображения атрибутов), а логическая - связи между таблицами

**Comment by wldmr-key** [comment]
это один из видов концептуальных схем, который имеет право на существование, если ее читателю понятно, что имеется в виду. Без атрибутов (и/или примеров) этот вид допускает множество интерпретаций, как правильных (соответствующих твоему описанию предметной области), так и неправильных, вроде тех, что делаешь ты

Я бы предположил, что расписание тренера - это его график работы (без занятий), а расписание клиента... Хм.. Тебе виднее. Возможно, время посещения зала без тренера. 
Занятия - это то место, где клиент и тренер пересекаются.
Здесь мне все видится логичным. Пока ты не начинаешь треш с атрибутами


> Мне казалось, что концептуальная схема должна отображать хранение информации в БД (с помощью отображения атрибутов), а логическая - связи между таблицами

Это не так

**Comment by Kirill1371** [comment]
Мне видится что график работы - это фиксированное время момента начала и момента конца, тогда как расписание - уточнение работы по часам. Разве тренеру не нужно знать наперёд чем он будет заниматься в тот или иной день?

**Comment by Kirill1371** [comment]
Если я правильно Вас понял, то имеет место быть такая концептуальная схема в моём случае, т.к. она соответствует предметной области
![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/868d4f82-e6b7-4c9b-9751-b0157a95a2a9)

**Comment by Kirill1371** [comment]
Прошу прощения, вот такая концептуальная схема*

![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/2f919835-b5ae-4506-a384-4d9def73efa3)

**Comment by wldmr-key** [comment]
> Мне видится что график работы - это фиксированное время момента начала и момента конца, тогда как расписание - уточнение работы по часам. Разве тренеру не нужно знать наперёд чем он будет заниматься в тот или иной день?

стоп! Расшифровки понятия "график" в описании предметной области нет! К чему здесь эта фантазия? Что за уточнение? Прочитай, что ты сам там написал!

Картинка - нет-нет-нет. Пока становится только хуже. Та, которую я комментировал (без атрибутов) вполне подходила при правильной интерпретации

**Comment by Kirill1371** [comment]
Изменённые концептуальная и логические схемы (последняя с наполнением)

![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/f8de6872-054e-4b65-aca0-68f331e969ba)


![image](https://github.com/Kirill1371/Kup_3_sem/assets/144225525/739d4573-d7a0-4f03-b802-15ca0d905119)

**Comment by wldmr-key** [comment]
норм толькуо названия у коллекций перечитай, плиз
