### ISSUE TITLE
Проектно-технологическая часть

### ISSUE THREAD

**Issue by Kirill1371** [Kirill1371/Kup_3_sem#9]
5.1 Проектирование начального и тестового наполнения базы данных. Порядок развертывания системы.
1) Добавить в MongoDB IP-адрес, с которого будут поступать запросы от сервера
2) Открыть папку с проектом в IDE поддерживающим JavaScript
3) Запустить команду “npm run dev” в терминале
4) Дождаться запуска сервера и клиентской части
5) Открыть http://localhost:3000

Для изменения внешнего вида веб-приложения можно загрузить изображения или изменить вёрстку страниц.
Также необходимо зарегистрировать пользователей и выдать им доступ к их аккаунтам для работы в системе. 

Примеры наполнения приведены в пункте 4.3

**Comment by wldmr-key** [comment]
ох...
при твоем порядке с системой можно будут работать только с одного компьютера

**Comment by Kirill1371** [comment]
А это плохо? В начале семестра Вы говорили что это не важно

**Comment by wldmr-key** [comment]
> А это плохо? В начале семестра Вы говорили что это не важно

скорее всего, или я неправильно выразился, или ты неправильно интерпретировал. Да, вы пишете игрушечную систему, но вы должны продемонстрировать понимание отличий игрушечной от настоящей

**Comment by Kirill1371** [comment]
Мне стоит выложить свою систему в открытый доступ в интернет?

**Comment by wldmr-key** [comment]
не стоит... )
тебе нужно написать порядок ее развертывания, чтобы ей можно было пользоваться
